import Storycard from "../components/Storycard.js";

export default function Author() {
  return (
    <div>
      <Storycard
        img="https://i.pinimg.com/736x/38/e7/b9/38e7b914934c8057154e6072d4566a1f.jpg"
        section="Author"
        author="Wikipedia"
        ogLink="https://en.wikipedia.org/wiki/Eiichiro_Oda"
        title="Oda Eiichiro - The Legendary Manga Artist Behind One Piece"
        content1={`Eiichiro Oda (Japanese: 尾田 栄一郎, Hepburn: Oda Eiichirō, born January 1, 1975) is a Japanese manga artist and the creator of the series One Piece (1997–present). With more than 516.5 million tankōbon copies in circulation worldwide, One Piece is both the best-selling manga in history and the best-selling comic series printed in volume, in turn making Oda one of the best-selling fiction authors. The series' popularity resulted in Oda being named one of the manga artists that changed the history of manga. Life: Eiichiro Oda was born on January 1, 1975, in Kumamoto, Japan. He said that at the age of four he resolved to become a manga artist in order to avoid having to get a "real job". His biggest influence is Akira Toriyama and his series Dragon Ball. He recalls that his interest in pirates was probably sparked by the popular TV animation series titled Vicky the Viking. He submitted a character named Pandaman for Yudetamago's classic wrestling manga Kinnikuman. Pandaman was not only used in a chapter of the manga but would later return as a recurring cameo character in Oda's own works.`}
        content2={`The Early Life: Eiichiro Oda was born on January 1, 1975, in Kumamoto, Japan. He said that at the age of four he resolved to become a manga artist in order to avoid having to get a "real job". His biggest influence is Akira Toriyama and his series Dragon Ball. He recalls that his interest in pirates was probably sparked by the popular TV animation series titled Vicky the Viking. He submitted a character named Pandaman for Yudetamago's classic wrestling manga Kinnikuman. Pandaman was not only used in a chapter of the manga but would later return as a recurring cameo character in Oda's own works.
        spawned a media franchise, having been adapted into a festival film produced by Production I.G, and an anime series produced by Toei Animation, which began broadcasting in Japan in 1999. Additionally, Toei has developed fourteen animated feature films, one original video animation and thirteen television specials. Several companies have developed various types of merchandising and media, such as a trading card game and numerous video games. The manga series was licensed for an English language release in North America and the United Kingdom by Viz Media and in Australia by Madman Entertainment. The anime series was licensed by 4Kids Entertainment for an English-language release in North America in 2004, before the license was dropped and subsequently acquired by Funimation in 2007.`}
        content3={`One Piece has At the age of 17, Oda submitted his work Wanted! and won several awards, including second place in the coveted Tezuka Award. That got him into a job at the Weekly Shōnen Jump magazine, where he originally worked as assistant manga artist/assistant to Shinobu Kaitani's series Suizan Police Gang before moving to Masaya Tokuhiro on Jungle King Tar-chan and Mizu no Tomodachi Kappaman,which gave him an unexpected influence on his artistic style. At the age of 19, he began working as an assistant to Nobuhiro Watsuki on Rurouni Kenshin, before winning the Hop Step Award for new manga artists. Watsuki credits Oda for helping create the character Honjō Kamatari who appears in Rurouni Kenshin.
        praise for its storytelling, art, characterization, and humor. It has received many awards and is ranked by critics, reviewers, and readers as one of the best manga of all time. Several volumes of the manga have broken publishing records, including the highest initial print run of any book in Japan. In 2015 and 2022, One Piece set the Guinness World Record for "the most copies published for the same comic book series by a single author". It was the best-selling manga for eleven consecutive years from 2008 to 2018, and is the only manga that had an initial print of volumes of above 3 million continuously for more than 10 years, as well as the only that had achieved more than 1 million copies sold in all of its over 100 published tankōbon volumes. One Piece is the only manga whose volumes have ranked first every year in Oricon's weekly comic chart existence since 2008.`}
      />
    </div>
  );
}
